CREATE TABLE IF NOT EXISTS subscribers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  subscribed_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  unsubscribe_token TEXT NOT NULL UNIQUE
);
